# copy_text.py — every word on the page, English and Thai, written by hand.

NAV = ["koch", "chaos", "tree", "fern", "dragon", "mandel", "julia", "coast", "make", "nature", "history"]

UI = {
    "en": {
        "title": "Play with Fractals",
        "other_title": "เล่นกับแฟร็กทัล",
        "desc": "Fractals to play with, drawn live: the Koch snowflake, the chaos game, a tree, Barnsley's fern, the paper-folding dragon, the Mandelbrot and Julia sets, a coastline to measure and your own fractal with its dimension. In English and Thai.",
        "card_alt": "The Mandelbrot set in gold on night blue, with the title Play with Fractals",
        "hero_alt": "The Mandelbrot set, zooming slowly into Seahorse Valley",
        "kicker": "Shapes built from smaller copies of themselves",
        "lede": "Zoom, fold, grow and scatter. The drawings here grow live from a rule or two.",
        "hero_go": "Take the wheel",
        "cardline": "Nine toys, in English and Thai",
        "nav_label": "Sections",
        "nav": ["Snowflake", "Chaos game", "Tree", "Fern", "Dragon", "Mandelbrot", "Julia", "Coast", "Make", "Nature", "History"],
        "lang_this": "EN",
        "lang_other": ("th/", "ไทย", "th"),

        "what_kick": "Fractals",
        "what_h": "Broken, and the same all the way down",
        "what_p": [
            "A fractal is a shape that holds smaller copies of itself, with smaller copies inside those, as far down as you care to look. A fern frond is made of little fronds; a branch looks like a small tree; a stretch of coast looks like a whole coast.",
            "Benoit Mandelbrot named them in 1975, from the Latin <i>fractus</i>, broken. Mathematicians had been drawing such shapes for a hundred years and calling them monsters, because they broke the old rules about length, area and dimension.",
            "Most come from a short rule repeated many times. Each toy below shows its rule. Press the buttons and watch it run.",
        ],

        "koch_kick": "Helge von Koch, 1904",
        "koch_h": "A snowflake with an endless edge",
        "koch_p": [
            "Start with a triangle. Cut each side in three and raise a small triangle on the middle third. Do the same to the new sides, and again.",
            "Each step turns one side into four, each a third as long, so the outline grows by 4/3. After ten steps it is 18 times as long; after a hundred, three trillion times. The area grows by less each step and settles at 8/5 of the first triangle: an outline with no end around a patch you could paint.",
        ],
        "koch_note": "Level 7 has 49,152 sides. Your screen runs out of pixels long before the rule runs out of steps. Zoom forever rides down one side: a third of a side looks like the whole side, so the picture loops.",
        "k_level": "Level", "k_sides": "Sides", "k_outline": "Outline", "k_area": "Area", "k_zoom": "Zoom forever",

        "chaos_kick": "A game of chance",
        "chaos_h": "Roll dice, get a triangle",
        "chaos_p": [
            "Put three corners on the page and a dot anywhere. Pick a corner at random, move the dot halfway to it, and mark where it lands. Repeat.",
            "You might expect a smudge. Out comes Wacław Sierpiński's triangle of 1915: a triangle with its middle cut out, the middle cut out of the three left over, and so on down. Michael Barnsley called this the chaos game.",
            "Change the corners and the jump. Fit picks the jump at which the copies just touch. Four corners and a halfway jump fill the square solid; forbid the same corner twice and a pattern comes back.",
        ],
        "chaos_note": "Tap the picture to drop the dot somewhere new. One jump draws the move as a line.",
        "g_corners": "Corners", "g_jump": "Jump, share of the way", "g_fit": "Fit",
        "g_rules": ["Any corner", "Not the same twice", "Not the next one clockwise"],
        "g_step": "One jump", "g_clear": "Clear", "g_dots": "Dots",

        "tree_kick": "Branches",
        "tree_h": "A tree from one rule",
        "tree_p": [
            "Draw a trunk. At its top draw two shorter branches, one turned left and one right. Treat each branch as a trunk and do it again.",
            "Each level doubles the tips: ten levels make 1,024, thirteen make 8,192. If each branch is under half the length of its parent, the whole tree has a finite length however many levels you add. At half or more, the total grows without limit.",
            "Rivers, lungs, lightning and blood vessels branch in the same manner. Move across the tree to bend it.",
        ],
        "t_levels": "Levels", "t_angle": "Angle", "t_shrink": "Shrink", "t_wind": "Wind", "t_bloom": "Blossom",
        "t_tips": "Tips", "t_length": "Total length",

        "fern_kick": "Four moves",
        "fern_h": "A fern from four moves",
        "fern_p": [
            "Michael Barnsley's fern, from his 1988 book <i>Fractals Everywhere</i>, plays the chaos game with four moves in place of corners. Each move shrinks, turns and shifts the whole picture: one makes the stem, one the rest of the frond above the lowest pair of leaflets, one the left leaflet and one the right.",
            "The big move comes up 85 times in a hundred, the stem once, each leaflet 7 times. Pick a move at random, apply it to the dot, mark it, repeat. Lean and Leaflets change the numbers inside the moves; Colour by move shows which move put down each dot.",
        ],
        "f_lean": "Lean", "f_leaf": "Leaflets", "f_colour": "Colour by move", "f_dots": "Dots",

        "dragon_kick": "Paper folding",
        "dragon_h": "Fold a strip, get a dragon",
        "dragon_p": [
            "Fold a strip of paper in half, in half again the same way, and again. Open it so each crease makes a right angle. Ten folds give 1,024 pieces in the shape of a dragon.",
            "NASA physicists John Heighway, Bruce Banks and William Harter found it; Martin Gardner wrote it up in <i>Scientific American</i> in 1967. The curve touches itself at corners but does not cross, and four dragons turned four ways fit together around a point with no overlap.",
            "The creases read R R L R R L L R R R L L R L L …, the paper-folding sequence. The odd creases alternate R, L; the even ones repeat the whole sequence.",
        ],
        "d_folds": "Folds", "d_unfold": "Unfold", "d_four": "Four dragons", "d_pieces": "Pieces", "d_creases": "Creases",
        "d_R": "R", "d_L": "L",

        "mandel_kick": "z → z² + c",
        "mandel_h": "The Mandelbrot set",
        "mandel_p": [
            "Pick a point c on the picture; it stands for a number with two parts, a complex number. Start at zero, square it and add c. Square the answer and add c again. Repeat.",
            "Some points fly off; some stay near home however long you go. The ones that stay make the dark shape. Colour shows how fast the rest leave. Move over the picture, or tap, to see a point's path.",
            "Drag to move, scroll or pinch to zoom, double-click to dive. Small copies of the whole set sit along the edge, joined by threads, with more along theirs. This toy stops near 200,000 times, where the computer's numbers run out of digits; the set goes on.",
        ],
        "mandel_note": "Robert Brooks and Peter Matelski printed a rough picture of it in 1978; Mandelbrot's pictures at IBM from 1980 made it famous. Its area is about 1.5066. In 1998 Mitsuhiro Shishikura proved its edge has dimension 2, as crinkled as a curve in a plane can be.",
        "m_places": "Places",
        "places": ["Whole", "Seahorse valley", "Elephant valley", "Double spiral", "Baby set", "Lightning"],
        "m_steps": "Steps", "m_colours": "Colours",
        "colours": ["Gold", "Sea", "Fire", "Candy"],
        "m_zoom": "Zoom", "m_point": "Point", "m_path": "Path",
        "m_stays": "stays near home", "m_leaves": "leaves at step {n}",
        "m_in": "Zoom in", "m_out": "Zoom out",

        "julia_kick": "One c, one picture",
        "julia_h": "Julia sets",
        "julia_p": [
            "Keep c fixed and start each point of the picture from where it sits instead of from zero. The points that stay make a Julia set, after Gaston Julia, who studied them in 1918 while Pierre Fatou did the same, with no computer to draw them.",
            "Move over the small map to choose c. With c inside the Mandelbrot set, the Julia set comes in one piece; outside, it falls to dust. The wildest ones sit near the edge.",
        ],
        "j_walk": "Walk the edge", "j_map": "Map of c", "j_one": "one piece", "j_dust": "dust",

        "coast_kick": "How long is a coast?",
        "coast_h": "Measure a coastline",
        "coast_p": [
            "Lewis Fry Richardson measured coasts and borders with shorter and shorter rulers, and the totals kept growing. Spain and Portugal gave lengths for their shared border more than 200 km apart. His figures came out in 1961, after his death; Mandelbrot took them up in 1967 in “How long is the coast of Britain?”",
            "Walk the made-up coast below with a pair of dividers. Halve the ruler and the coast comes out about a fifth longer. Plot length against ruler on log scales and the points fall along a line; one minus its slope is the dimension. A smooth curve scores 1, this coast about 1.26, the west coast of Britain about 1.25 by Richardson's figures.",
        ],
        "coast_note": "The coast is 1,000 km from end to end. Below about 2 km the made-up coast runs out of wiggles and stops growing; a coast outdoors carries on down to rocks and grains of sand.",
        "c_ruler": "Ruler", "c_steps": "Steps", "c_len": "Length", "c_dim": "Dimension", "c_new": "New coast", "km": "km",
        "c_axis_x": "ruler, km", "c_axis_y": "length, km",

        "make_kick": "Dimension",
        "make_h": "Make your own",
        "make_p": [
            "Cut a line into 3 and you get 3 copies, each a third the size: 3 = 3¹. A square gives 9 = 3², a cube 27 = 3³. The power is the dimension. The Koch curve gives 4 copies at a third: 4 = 3<sup>D</sup>, so D = log 4 / log 3 ≈ 1.26, between a line and a plane.",
            "Drag the dots of the bent line, tap the line to add a dot, double-tap a dot to remove it. Each straight piece is replaced by the whole bent line, level after level. With pieces of lengths r₁, r₂, …, the dimension D solves r₁<sup>D</sup> + r₂<sup>D</sup> + … = 1.",
        ],
        "make_note": "If pieces cross or overlap, the shape fills less than this number says.",
        "y_from": "Start from",
        "presets": ["Koch", "Square wave", "Lévy C", "Peano", "Tall Koch"],
        "y_levels": "Levels", "y_pieces": "Pieces", "y_dim": "Dimension", "y_segs": "Segments", "y_save": "Save picture",
        "y_hint": "drag the dots",

        "nature_kick": "Out of doors",
        "nature_h": "Found in nature",
        "nature_p": [
            "Nature's fractals run out after a few levels, at the size of a cell or a crystal of ice, but the pattern shows. In Thai the Romanesco is กะหล่ำดอกเจดีย์, the pagoda cauliflower.",
            "Thai ornament grows flames on flames: see <a href=\"https://nanobotco.github.io/kranok/#nest\">Kranok, Drawn</a>.",
        ],
        "photo": {
            "romanesco": "Romanesco: cones of cones, in spirals.",
            "fern": "Ostrich fern fiddleheads unrolling, curls within curls.",
            "delta": "The Lena River Delta, Siberia, from Landsat 7, 2000.",
            "lightning": "Lightning over Albury, New South Wales, branching as it goes.",
            "snowflake": "Snowflakes photographed by Wilson Bentley, Vermont, 1902.",
            "prang": "The central prang of Wat Arun, Bangkok: smaller towers echo the tall one, tier on tier.",
            "tree": "A rain tree (จามจุรี) in Sukhothai Historical Park.",
        },

        "hist_kick": "History",
        "hist_h": "Monsters to pictures",
        "hist": [
            ("1883", "Georg Cantor takes a line, removes its middle third, then the middle thirds of what is left, without end. Dust remains."),
            ("1904", "Helge von Koch's snowflake curve: a curve with no tangent at any point."),
            ("1915", "Wacław Sierpiński's triangle."),
            ("1918", "Gaston Julia and Pierre Fatou work out Julia sets on paper."),
            ("1961", "Lewis Fry Richardson's coast and border measurements are published."),
            ("1967", "Mandelbrot asks how long the coast of Britain is. Martin Gardner's column carries the dragon curve."),
            ("1975", "Mandelbrot coins the word fractal."),
            ("1978", "Robert Brooks and Peter Matelski print the first picture of the Mandelbrot set."),
            ("1980", "Mandelbrot's computer pictures at IBM."),
            ("1982", "<i>The Fractal Geometry of Nature</i>."),
            ("1988", "Michael Barnsley's <i>Fractals Everywhere</i>: the fern and the chaos game."),
            ("1998", "Mitsuhiro Shishikura: the edge of the Mandelbrot set has dimension 2."),
        ],
        "words_h": "Words",
        "src_h": "Sources",
        "src_p": "Facts on this page come from these. Photographs come from Wikimedia Commons, each credited where it appears.",
        "foot": "Text CC BY 4.0, NaNoBotCo. Code MIT. Photographs keep their own licences.",

        "js": {
            "growing": "and growing",
            "inside": "inside",
            "outside": "outside",
        },
    },

    "th": {
        "title": "เล่นกับแฟร็กทัล",
        "other_title": "Play with Fractals",
        "desc": "แฟร็กทัลให้เล่น วาดสด ๆ ตรงหน้า: เกล็ดหิมะค็อค เกมความอลวน ต้นไม้ เฟิร์นของบาร์นสลีย์ มังกรพับกระดาษ เซตม็องแดลโบรตและเซตจูเลีย ชายฝั่งให้ลองวัด และแฟร็กทัลของคุณเองพร้อมมิติ ภาษาไทยและอังกฤษ",
        "card_alt": "เซตม็องแดลโบรตสีทองบนพื้นน้ำเงินกลางคืน พร้อมชื่อ เล่นกับแฟร็กทัล",
        "hero_alt": "เซตม็องแดลโบรต ค่อย ๆ ซูมเข้าไปในหุบม้าน้ำ",
        "kicker": "รูปร่างที่ประกอบขึ้นจากสำเนาเล็ก ๆ ของตัวมันเอง",
        "lede": "ซูม พับ ปลูก และโปรย ภาพในหน้านี้งอกขึ้นสด ๆ จากกฎเพียงหนึ่งหรือสองข้อ",
        "hero_go": "ลองขับเอง",
        "cardline": "ของเล่นเก้าชิ้น ภาษาไทยและอังกฤษ",
        "nav_label": "หัวข้อ",
        "nav": ["เกล็ดหิมะ", "เกมสุ่ม", "ต้นไม้", "เฟิร์น", "มังกร", "ม็องแดลโบรต", "จูเลีย", "ชายฝั่ง", "สร้างเอง", "ธรรมชาติ", "ประวัติ"],
        "lang_this": "ไทย",
        "lang_other": ("../", "EN", "en"),

        "what_kick": "แฟร็กทัล",
        "what_h": "แตกเป็นชิ้น และเหมือนเดิมไปจนสุดทาง",
        "what_p": [
            "แฟร็กทัลคือรูปร่างที่มีสำเนาขนาดเล็กของตัวเองอยู่ข้างใน และในสำเนานั้นก็มีสำเนาที่เล็กลงไปอีก ลึกลงไปเท่าที่อยากดู ใบเฟิร์นหนึ่งใบประกอบด้วยใบเฟิร์นเล็ก ๆ กิ่งไม้หนึ่งกิ่งดูเหมือนต้นไม้ต้นเล็ก ชายฝั่งช่วงสั้น ๆ ดูเหมือนชายฝั่งทั้งเส้น",
            "เบอนัว ม็องแดลโบรต ตั้งชื่อนี้ในปี 1975 จากคำละติน <i>fractus</i> ที่แปลว่าแตกหัก ก่อนหน้านั้นนักคณิตศาสตร์วาดรูปแบบนี้มาร้อยปีแล้ว และเรียกมันว่าสัตว์ประหลาด เพราะมันฝ่ากฎเดิมเรื่องความยาว พื้นที่ และมิติ",
            "แฟร็กทัลส่วนใหญ่เกิดจากกฎสั้น ๆ ที่ทำซ้ำหลายครั้ง ของเล่นแต่ละชิ้นข้างล่างบอกกฎของมันไว้ กดปุ่มแล้วดูมันทำงาน",
        ],

        "koch_kick": "เฮลเกอ ฟอน ค็อค ปี 1904",
        "koch_h": "เกล็ดหิมะที่ขอบยาวไม่รู้จบ",
        "koch_p": [
            "เริ่มจากสามเหลี่ยมหนึ่งรูป แบ่งแต่ละด้านเป็นสามส่วน แล้วตั้งสามเหลี่ยมเล็ก ๆ ขึ้นบนส่วนกลาง ทำแบบเดียวกันกับด้านใหม่ แล้วทำอีก",
            "แต่ละขั้นเปลี่ยนด้านหนึ่งด้านเป็นสี่ด้าน ยาวด้านละหนึ่งในสาม เส้นรอบรูปจึงยาวขึ้น 4/3 เท่า สิบขั้นยาวขึ้น 18 เท่า ร้อยขั้นยาวขึ้นสามล้านล้านเท่า ส่วนพื้นที่โตขึ้นน้อยลงทุกขั้น และไปหยุดที่ 8/5 ของสามเหลี่ยมแรก เป็นเส้นรอบรูปที่ยาวไม่สิ้นสุด ล้อมพื้นที่ที่ทาสีได้หมด",
        ],
        "koch_note": "ขั้นที่ 7 มี 49,152 ด้าน พิกเซลบนจอหมดก่อนกฎจะหมดขั้นเสียอีก ปุ่ม ซูมไม่รู้จบ พาไล่ลงไปตามด้านหนึ่ง หนึ่งในสามของด้านหน้าตาเหมือนทั้งด้าน ภาพจึงวนซ้ำได้",
        "k_level": "ขั้น", "k_sides": "จำนวนด้าน", "k_outline": "เส้นรอบรูป", "k_area": "พื้นที่", "k_zoom": "ซูมไม่รู้จบ",

        "chaos_kick": "เกมเสี่ยงทาย",
        "chaos_h": "ทอยลูกเต๋า ได้สามเหลี่ยม",
        "chaos_p": [
            "วางมุมสามมุมบนหน้ากระดาษ แล้ววางจุดไว้ตรงไหนก็ได้ สุ่มเลือกมุมหนึ่ง เลื่อนจุดไปครึ่งทางสู่มุมนั้น แล้วทำเครื่องหมายตรงที่จุดตก ทำซ้ำ",
            "หลายคนคิดว่าจะได้รอยเปื้อนมั่ว ๆ แต่ที่ออกมาคือสามเหลี่ยมของวาตสวัฟ เซียร์ปินสกี จากปี 1915 สามเหลี่ยมที่เจาะตรงกลางออก แล้วเจาะกลางของสามรูปที่เหลือ ไล่ลงไปเรื่อย ๆ ไมเคิล บาร์นสลีย์ เรียกวิธีนี้ว่าเกมความอลวน",
            "ลองเปลี่ยนจำนวนมุมและระยะกระโดด ปุ่ม พอดี เลือกระยะที่ทำให้สำเนาแตะกันพอดี สี่มุมกับกระโดดครึ่งทางจะถมสี่เหลี่ยมจนเต็ม แต่ถ้าห้ามเลือกมุมเดิมซ้ำ ลวดลายจะกลับมา",
        ],
        "chaos_note": "แตะภาพเพื่อวางจุดใหม่ ปุ่ม กระโดดทีละครั้ง วาดการเคลื่อนเป็นเส้นให้ดู",
        "g_corners": "มุม", "g_jump": "ระยะกระโดด (สัดส่วนของทาง)", "g_fit": "พอดี",
        "g_rules": ["มุมไหนก็ได้", "ห้ามมุมเดิมซ้ำ", "ห้ามมุมถัดไปตามเข็มนาฬิกา"],
        "g_step": "กระโดดทีละครั้ง", "g_clear": "ล้าง", "g_dots": "จุด",

        "tree_kick": "กิ่งก้าน",
        "tree_h": "ต้นไม้จากกฎข้อเดียว",
        "tree_p": [
            "วาดลำต้น ที่ปลายลำต้นวาดกิ่งที่สั้นกว่าสองกิ่ง เอียงซ้ายหนึ่ง ขวาหนึ่ง แล้วถือว่าแต่ละกิ่งเป็นลำต้นใหม่ ทำซ้ำ",
            "ทุกชั้นปลายกิ่งเพิ่มเป็นสองเท่า สิบชั้นได้ 1,024 ปลาย สิบสามชั้นได้ 8,192 ถ้ากิ่งแต่ละกิ่งยาวไม่ถึงครึ่งของกิ่งแม่ ความยาวรวมของทั้งต้นจะมีขอบเขต ต่อให้เพิ่มชั้นไปเท่าไรก็ตาม ถ้ายาวครึ่งหนึ่งหรือมากกว่า ความยาวรวมจะโตไม่มีที่สิ้นสุด",
            "แม่น้ำ ปอด ฟ้าผ่า และเส้นเลือด แตกกิ่งแบบเดียวกัน ลากผ่านต้นไม้เพื่อให้มันเอน",
        ],
        "t_levels": "ชั้น", "t_angle": "มุม", "t_shrink": "ย่อ", "t_wind": "ลม", "t_bloom": "ออกดอก",
        "t_tips": "ปลายกิ่ง", "t_length": "ความยาวรวม",

        "fern_kick": "สี่ท่า",
        "fern_h": "เฟิร์นจากสี่ท่า",
        "fern_p": [
            "เฟิร์นของไมเคิล บาร์นสลีย์ จากหนังสือ <i>Fractals Everywhere</i> ปี 1988 คือเกมความอลวนที่ใช้สี่ท่าแทนมุม แต่ละท่าย่อ หมุน และเลื่อนทั้งภาพ ท่าหนึ่งสร้างก้าน ท่าหนึ่งสร้างส่วนที่เหลือของใบเหนือใบย่อยคู่ล่างสุด ท่าหนึ่งสร้างใบย่อยซ้าย อีกท่าสร้างใบย่อยขวา",
            "ท่าใหญ่ถูกสุ่มได้ 85 ครั้งในร้อย ก้าน 1 ครั้ง ใบย่อยข้างละ 7 ครั้ง สุ่มท่า ใช้กับจุด ทำเครื่องหมาย ทำซ้ำ ตัวเลื่อน เอน และ ใบย่อย เปลี่ยนตัวเลขในท่า ปุ่ม แยกสีตามท่า บอกว่าจุดแต่ละจุดมาจากท่าไหน",
        ],
        "f_lean": "เอน", "f_leaf": "ใบย่อย", "f_colour": "แยกสีตามท่า", "f_dots": "จุด",

        "dragon_kick": "พับกระดาษ",
        "dragon_h": "พับแถบกระดาษ ได้มังกร",
        "dragon_p": [
            "พับแถบกระดาษครึ่งหนึ่ง พับครึ่งอีกครั้งไปทางเดิม แล้วพับอีก คลี่ออกให้รอยพับแต่ละรอยเป็นมุมฉาก พับสิบครั้งได้ 1,024 ท่อน เป็นรูปมังกร",
            "นักฟิสิกส์ของนาซา จอห์น ไฮเวย์ บรูซ แบงส์ และวิลเลียม ฮาร์เตอร์ เป็นผู้พบ มาร์ติน การ์ดเนอร์ นำไปเขียนในนิตยสาร <i>Scientific American</i> ปี 1967 เส้นนี้แตะตัวเองที่มุมแต่ไม่ตัดกัน และมังกรสี่ตัวที่หันไปสี่ทิศต่อกันรอบจุดเดียวได้โดยไม่ซ้อนทับ",
            "รอยพับอ่านได้ว่า ข ข ซ ข ข ซ ซ ข ข ข ซ ซ ข ซ ซ … (ข = ขวา ซ = ซ้าย) เรียกว่าลำดับการพับกระดาษ รอยพับลำดับคี่สลับ ข ซ ส่วนลำดับคู่ซ้ำทั้งลำดับเดิม",
        ],
        "d_folds": "พับ", "d_unfold": "คลี่", "d_four": "มังกรสี่ตัว", "d_pieces": "ท่อน", "d_creases": "รอยพับ",
        "d_R": "ข", "d_L": "ซ",

        "mandel_kick": "z → z² + c",
        "mandel_h": "เซตม็องแดลโบรต",
        "mandel_p": [
            "เลือกจุด c บนภาพ จุดนั้นแทนจำนวนที่มีสองส่วน เรียกว่าจำนวนเชิงซ้อน เริ่มจากศูนย์ ยกกำลังสองแล้วบวก c เอาคำตอบมายกกำลังสองแล้วบวก c อีก ทำซ้ำ",
            "บางจุดพุ่งหนีออกไป บางจุดวนอยู่ใกล้บ้านไม่ว่าจะทำไปนานแค่ไหน จุดที่อยู่รวมกันเป็นรูปสีเข้ม สีของที่เหลือบอกว่ามันหนีเร็วแค่ไหน เลื่อนเมาส์บนภาพ หรือแตะ เพื่อดูเส้นทางของจุดนั้น",
            "ลากเพื่อเลื่อน หมุนล้อหรือถ่างนิ้วเพื่อซูม ดับเบิลคลิกเพื่อดำดิ่ง ตามขอบมีสำเนาเล็ก ๆ ของทั้งเซตเรียงอยู่ เชื่อมกันด้วยเส้นใย และตามขอบของสำเนาก็มีอีก ของเล่นนี้หยุดที่ราว 200,000 เท่า ตรงที่ตัวเลขในคอมพิวเตอร์หมดหลัก แต่เซตยังไปต่อ",
        ],
        "mandel_note": "โรเบิร์ต บรูกส์ และปีเตอร์ มาเทลสกี พิมพ์ภาพหยาบ ๆ ของมันในปี 1978 ภาพของม็องแดลโบรตที่ IBM ตั้งแต่ปี 1980 ทำให้มันโด่งดัง พื้นที่ของมันประมาณ 1.5066 ปี 1998 มิตสึฮิโระ ชิชิกุระ พิสูจน์ว่าขอบของมันมีมิติเท่ากับ 2 หยักมากที่สุดเท่าที่เส้นบนระนาบจะหยักได้",
        "m_places": "จุดแวะ",
        "places": ["ทั้งตัว", "หุบม้าน้ำ", "หุบช้าง", "เกลียวคู่", "ม็องแดลโบรตจิ๋ว", "สายฟ้า"],
        "m_steps": "จำนวนรอบ", "m_colours": "สี",
        "colours": ["ทอง", "ทะเล", "ไฟ", "ลูกกวาด"],
        "m_zoom": "ซูม", "m_point": "จุด", "m_path": "เส้นทาง",
        "m_stays": "วนอยู่ใกล้บ้าน", "m_leaves": "หนีออกที่รอบ {n}",
        "m_in": "ซูมเข้า", "m_out": "ซูมออก",

        "julia_kick": "c หนึ่งค่า ภาพหนึ่งภาพ",
        "julia_h": "เซตจูเลีย",
        "julia_p": [
            "ตรึง c ไว้ แล้วให้แต่ละจุดบนภาพเริ่มจากตำแหน่งของตัวเองแทนที่จะเริ่มจากศูนย์ จุดที่วนอยู่ใกล้บ้านรวมกันเป็นเซตจูเลีย ตั้งชื่อตามกัสตอง จูเลีย ผู้ศึกษามันในปี 1918 ขณะที่ปีแยร์ ฟาตู ก็ศึกษาเรื่องเดียวกัน โดยไม่มีคอมพิวเตอร์ช่วยวาด",
            "เลื่อนบนแผนที่เล็กเพื่อเลือก c ถ้า c อยู่ในเซตม็องแดลโบรต เซตจูเลียจะเป็นชิ้นเดียว ถ้าอยู่นอก มันจะแตกเป็นผงฝุ่น ภาพที่พิสดารที่สุดอยู่ใกล้ขอบ",
        ],
        "j_walk": "เดินตามขอบ", "j_map": "แผนที่ของ c", "j_one": "ชิ้นเดียว", "j_dust": "ผงฝุ่น",

        "coast_kick": "ชายฝั่งยาวเท่าไร",
        "coast_h": "วัดความยาวชายฝั่ง",
        "coast_p": [
            "ลูอิส ฟราย ริชาร์ดสัน วัดชายฝั่งและเส้นพรมแดนด้วยไม้บรรทัดที่สั้นลงเรื่อย ๆ และผลรวมก็ยาวขึ้นเรื่อย ๆ สเปนกับโปรตุเกสให้ความยาวพรมแดนร่วมกันต่างกันกว่า 200 กิโลเมตร ตัวเลขของเขาตีพิมพ์ในปี 1961 หลังเขาเสียชีวิต ม็องแดลโบรตนำไปต่อยอดในปี 1967 ในบทความ “ชายฝั่งของบริเตนยาวเท่าไร”",
            "ลองเดินวงเวียนวัดไปตามชายฝั่งสมมุติข้างล่าง ลดไม้บรรทัดลงครึ่งหนึ่ง ชายฝั่งจะยาวขึ้นราวหนึ่งในห้า พล็อตความยาวกับขนาดไม้บรรทัดบนสเกลลอการิทึม จุดจะเรียงเป็นเส้นตรง หนึ่งลบความชันคือมิติ เส้นโค้งเรียบได้ 1 ชายฝั่งนี้ได้ราว 1.26 และชายฝั่งตะวันตกของบริเตนได้ราว 1.25 ตามตัวเลขของริชาร์ดสัน",
        ],
        "coast_note": "ชายฝั่งนี้ยาว 1,000 กิโลเมตรจากปลายถึงปลาย ต่ำกว่าราว 2 กิโลเมตร ชายฝั่งสมมุติจะหมดรอยหยักและหยุดยาวขึ้น ชายฝั่งนอกบ้านหยักต่อลงไปถึงก้อนหินและเม็ดทราย",
        "c_ruler": "ไม้บรรทัด", "c_steps": "ก้าว", "c_len": "ความยาว", "c_dim": "มิติ", "c_new": "ชายฝั่งใหม่", "km": "กม.",
        "c_axis_x": "ไม้บรรทัด กม.", "c_axis_y": "ความยาว กม.",

        "make_kick": "มิติ",
        "make_h": "สร้างเอง",
        "make_p": [
            "ตัดเส้นตรงเป็น 3 ส่วน ได้สำเนา 3 ชิ้น ขนาดหนึ่งในสาม: 3 = 3¹ สี่เหลี่ยมจัตุรัสได้ 9 = 3² ลูกบาศก์ได้ 27 = 3³ เลขชี้กำลังคือมิติ เส้นโค้งค็อคได้สำเนา 4 ชิ้น ขนาดหนึ่งในสาม: 4 = 3<sup>D</sup> ดังนั้น D = log 4 / log 3 ≈ 1.26 อยู่ระหว่างเส้นกับระนาบ",
            "ลากจุดบนเส้นหัก แตะบนเส้นเพื่อเพิ่มจุด แตะสองครั้งที่จุดเพื่อลบ เส้นตรงแต่ละท่อนจะถูกแทนด้วยเส้นหักทั้งเส้น ชั้นแล้วชั้นเล่า ถ้าท่อนยาว r₁, r₂, … มิติ D คือคำตอบของ r₁<sup>D</sup> + r₂<sup>D</sup> + … = 1",
        ],
        "make_note": "ถ้าท่อนตัดกันหรือซ้อนทับกัน รูปจะเต็มน้อยกว่าที่ตัวเลขนี้บอก",
        "y_from": "เริ่มจาก",
        "presets": ["ค็อค", "คลื่นเหลี่ยม", "เลวี ซี", "เปอาโน", "ค็อคสูง"],
        "y_levels": "ชั้น", "y_pieces": "ท่อน", "y_dim": "มิติ", "y_segs": "ส่วนของเส้น", "y_save": "บันทึกภาพ",
        "y_hint": "ลากจุดได้",

        "nature_kick": "นอกบ้าน",
        "nature_h": "พบในธรรมชาติ",
        "nature_p": [
            "แฟร็กทัลในธรรมชาติหมดลงหลังไม่กี่ชั้น ที่ขนาดของเซลล์หรือผลึกน้ำแข็ง แต่ลวดลายยังเห็นชัด กะหล่ำโรมาเนสโกในภาษาไทยเรียกว่ากะหล่ำดอกเจดีย์",
            "ลายไทยก็งอกเปลวบนเปลว ดูได้ที่ <a href=\"https://nanobotco.github.io/kranok/th/#nest\">กนก วาดด้วยคณิต</a>",
        ],
        "photo": {
            "romanesco": "กะหล่ำดอกเจดีย์: กรวยซ้อนกรวย เรียงเป็นเกลียว",
            "fern": "ยอดเฟิร์นนกกระจอกเทศกำลังคลี่ ขดในขด",
            "delta": "ปากแม่น้ำลีนา ไซบีเรีย จากดาวเทียมแลนด์แซต 7 ปี 2000",
            "lightning": "ฟ้าแลบเหนือเมืองออลเบอรี รัฐนิวเซาท์เวลส์ แตกกิ่งไปตลอดทาง",
            "snowflake": "เกล็ดหิมะที่วิลสัน เบนต์ลีย์ ถ่ายไว้ที่รัฐเวอร์มอนต์ ปี 1902",
            "prang": "พระปรางค์องค์กลาง วัดอรุณฯ กรุงเทพฯ: ปรางค์องค์เล็กรับปรางค์องค์ใหญ่ ซ้อนกันเป็นชั้น ๆ",
            "tree": "ต้นจามจุรีในอุทยานประวัติศาสตร์สุโขทัย",
        },

        "hist_kick": "ประวัติ",
        "hist_h": "จากสัตว์ประหลาดสู่ภาพ",
        "hist": [
            ("1883", "เกออร์ก คันทอร์ เอาเส้นตรงมาตัดหนึ่งในสามตรงกลางออก แล้วตัดหนึ่งในสามตรงกลางของส่วนที่เหลือ ไม่รู้จบ เหลือเป็นผงฝุ่น"),
            ("1904", "เส้นโค้งเกล็ดหิมะของเฮลเกอ ฟอน ค็อค เส้นโค้งที่ไม่มีเส้นสัมผัสที่จุดใดเลย"),
            ("1915", "สามเหลี่ยมของวาตสวัฟ เซียร์ปินสกี"),
            ("1918", "กัสตอง จูเลีย และปีแยร์ ฟาตู คิดเรื่องเซตจูเลียบนกระดาษ"),
            ("1961", "ผลการวัดชายฝั่งและพรมแดนของลูอิส ฟราย ริชาร์ดสัน ได้ตีพิมพ์"),
            ("1967", "ม็องแดลโบรตถามว่าชายฝั่งของบริเตนยาวเท่าไร คอลัมน์ของมาร์ติน การ์ดเนอร์ ลงเรื่องเส้นโค้งมังกร"),
            ("1975", "ม็องแดลโบรตตั้งคำว่าแฟร็กทัล"),
            ("1978", "โรเบิร์ต บรูกส์ และปีเตอร์ มาเทลสกี พิมพ์ภาพแรกของเซตม็องแดลโบรต"),
            ("1980", "ภาพจากคอมพิวเตอร์ของม็องแดลโบรตที่ IBM"),
            ("1982", "หนังสือ <i>The Fractal Geometry of Nature</i>"),
            ("1988", "หนังสือ <i>Fractals Everywhere</i> ของไมเคิล บาร์นสลีย์: เฟิร์นและเกมความอลวน"),
            ("1998", "มิตสึฮิโระ ชิชิกุระ: ขอบของเซตม็องแดลโบรตมีมิติเท่ากับ 2"),
        ],
        "words_h": "คำศัพท์",
        "src_h": "แหล่งข้อมูล",
        "src_p": "ข้อเท็จจริงในหน้านี้มาจากแหล่งเหล่านี้ ภาพถ่ายมาจากวิกิมีเดียคอมมอนส์ ให้เครดิตไว้ใต้ภาพแต่ละภาพ",
        "foot": "ข้อความ CC BY 4.0, NaNoBotCo โค้ด MIT ภาพถ่ายใช้สัญญาอนุญาตของแต่ละภาพ",

        "js": {
            "growing": "และยังโตต่อ",
            "inside": "อยู่ใน",
            "outside": "อยู่นอก",
        },
    },
}

# (English, Thai, English note, Thai note)
WORDS = [
    ("fractal", "แฟร็กทัล", "A shape with smaller copies of itself inside.", "รูปที่มีสำเนาขนาดเล็กของตัวเองอยู่ข้างใน"),
    ("self-similar", "คล้ายตัวเอง", "A part looks like the whole.", "ส่วนหนึ่งหน้าตาเหมือนทั้งหมด"),
    ("iterate", "ทำซ้ำ", "Feed the answer back into the same rule.", "ป้อนคำตอบกลับเข้ากฎเดิม"),
    ("dimension", "มิติ", "The power D in copies = scale<sup>D</sup>.", "เลขชี้กำลัง D ใน จำนวนสำเนา = อัตราย่อ<sup>D</sup>"),
    ("complex number", "จำนวนเชิงซ้อน", "A number with two parts, drawn as a point on a plane.", "จำนวนที่มีสองส่วน วาดเป็นจุดบนระนาบ"),
    ("escape time", "เวลาหนี", "Steps before z leaves the circle of radius 2.", "จำนวนรอบก่อน z ออกนอกวงกลมรัศมี 2"),
    ("chaos game", "เกมความอลวน", "Random jumps that draw a fixed picture.", "การกระโดดแบบสุ่มที่วาดภาพตายตัว"),
    ("iterated function system", "ระบบฟังก์ชันวนซ้ำ", "A set of shrinking moves, as in the fern.", "ชุดท่าที่ย่อภาพ อย่างในเฟิร์น"),
    ("coastline paradox", "ปฏิทรรศน์แนวชายฝั่ง", "A coast's length depends on the ruler.", "ความยาวชายฝั่งขึ้นกับไม้บรรทัด"),
    ("Koch snowflake", "เกล็ดหิมะค็อค", "Outline without end, area 8/5 of its triangle.", "เส้นรอบรูปยาวไม่รู้จบ พื้นที่ 8/5 ของสามเหลี่ยม"),
    ("Sierpiński triangle", "สามเหลี่ยมเซียร์ปินสกี", "3 copies at half size; dimension 1.585.", "สำเนา 3 ชิ้นขนาดครึ่งหนึ่ง มิติ 1.585"),
    ("dragon curve", "เส้นโค้งมังกร", "Paper folded in half again and again; edge dimension 1.524.", "กระดาษพับครึ่งซ้ำ ๆ ขอบมีมิติ 1.524"),
    ("Mandelbrot set", "เซตม็องแดลโบรต", "Points c whose path from zero stays near home.", "จุด c ที่เส้นทางจากศูนย์วนอยู่ใกล้บ้าน"),
    ("Julia set", "เซตจูเลีย", "For one c, the starting points that stay near home.", "สำหรับ c ค่าหนึ่ง คือจุดเริ่มที่วนอยู่ใกล้บ้าน"),
    ("Romanesco", "กะหล่ำดอกเจดีย์", "A cauliflower of cones made of cones.", "กะหล่ำที่มีกรวยประกอบจากกรวย"),
]

SOURCES = [
    ("Mandelbrot (1967), How Long Is the Coast of Britain? Science 156", "https://doi.org/10.1126/science.156.3775.636"),
    ("Shishikura (1998), The Hausdorff dimension of the boundary of the Mandelbrot set and Julia sets, Annals of Mathematics 147", "https://doi.org/10.2307/121009"),
    ("Wikipedia: Fractal", "https://en.wikipedia.org/wiki/Fractal"),
    ("Wikipedia: The Fractal Geometry of Nature", "https://en.wikipedia.org/wiki/The_Fractal_Geometry_of_Nature"),
    ("Wikipedia: Koch snowflake", "https://en.wikipedia.org/wiki/Koch_snowflake"),
    ("Wikipedia: Sierpiński triangle", "https://en.wikipedia.org/wiki/Sierpi%C5%84ski_triangle"),
    ("Wikipedia: Chaos game", "https://en.wikipedia.org/wiki/Chaos_game"),
    ("Wikipedia: Barnsley fern", "https://en.wikipedia.org/wiki/Barnsley_fern"),
    ("Wikipedia: Dragon curve", "https://en.wikipedia.org/wiki/Dragon_curve"),
    ("Wikipedia: Regular paperfolding sequence", "https://en.wikipedia.org/wiki/Regular_paperfolding_sequence"),
    ("Wikipedia: Mandelbrot set", "https://en.wikipedia.org/wiki/Mandelbrot_set"),
    ("Wikipedia: Julia set", "https://en.wikipedia.org/wiki/Julia_set"),
    ("Wikipedia: Coastline paradox", "https://en.wikipedia.org/wiki/Coastline_paradox"),
    ("Wikipedia: Lewis Fry Richardson", "https://en.wikipedia.org/wiki/Lewis_Fry_Richardson"),
    ("Wikipedia: Cantor set", "https://en.wikipedia.org/wiki/Cantor_set"),
    ("Wikipedia: List of fractals by Hausdorff dimension", "https://en.wikipedia.org/wiki/List_of_fractals_by_Hausdorff_dimension"),
    ("วิกิพีเดีย: แฟร็กทัล", "https://th.wikipedia.org/wiki/%E0%B9%81%E0%B8%9F%E0%B8%A3%E0%B9%87%E0%B8%81%E0%B8%97%E0%B8%B1%E0%B8%A5"),
    ("วิกิพีเดีย: กะหล่ำดอกเจดีย์", "https://th.wikipedia.org/wiki/%E0%B8%81%E0%B8%B0%E0%B8%AB%E0%B8%A5%E0%B9%88%E0%B8%B3%E0%B8%94%E0%B8%AD%E0%B8%81%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C"),
    ("Wikimedia Commons", "https://commons.wikimedia.org/"),
]
